### ISSUE TITLE
GoLang based examples

### ISSUE THREAD

**Issue by AdheipSingh** [kshitizsaini113/Data-Structure-and-Algorithms#4]
Can I  golang based examples in this repo. Can you list the workflow.

**Comment by kshitizsaini113** [comment]
yes
you can contribute, there is no restriction on language all the contributions are welcome

**Comment by kshitizsaini113** [comment]
Just post the example in the assigned folder and if no folder is of type please create a folder named Other

**Comment by AdheipSingh** [comment]
@kshitizsaini113 great thanks

**Comment by kshitizsaini113** [comment]
Will look forward towards your contributions.
